### PR TITLE
[#91] Remove Python venvs from EL externals builders

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Turns out, we don't actually need a venv at all.
Addresses #91

### CODE REVIEW

**Comment by korydraughn** [comment]
Will give this a try as soon as I can and let you know how it goes.

**Comment by trel** [comment]
but having a venv protects us against whatever is already on the host?   and keeps our stuff more consistent?

is that important / good?

also, do we know why it didn't work?

**Comment by SwooshyCueb** [comment]
> but having a venv protects us against whatever is already on the host? and keeps our stuff more consistent?
>
> is that important / good?

This is a docker image. Docker handles the separation from the host. We don't need the added complexity of a venv.

> also, do we know why it didn't work?

Because the venvs didn't have distro in them.

**Comment by trel** [comment]
Docker is the separation.   Got it, sold.

**Comment by korydraughn** [comment]
This PR fixes the issue for Almalinux 8.

It didn't work for CentOS 7 the **first** time I tried, but now it seems to be making progress following Almalinux's success. How is that possible? Could the `--mount` option to `RUN` be at play here?

Will post an update once CentOS 7 finishes. I'm going to try it again from a clean slate too.

**Comment by korydraughn** [comment]
To add to that, pkgs.org doesn't list python3-distro as an available package for CentOS 7. Hence, the need for the venv+pip in the externals README.

Will keep investigating.

**Comment by korydraughn** [comment]
Soooo, externals for CentOS 7 just finished building successfully using the externals builder image.

Trying again without any cache.

**Comment by SwooshyCueb** [comment]
> pkgs.org doesn't list python3-distro as an available package for CentOS 7.

`python3-distro` is provided by [`python36-distro`](https://rhel.pkgs.org/7/epel-x86_64/python36-distro-1.5.0-1.el7.noarch.rpm.html#required_by) from the EPEL repo.

> It didn't work for CentOS 7 the **first** time I tried, but now it seems to be making progress following Almalinux's success. How is that possible? Could the `--mount` option to `RUN` be at play here?

It's possible we need to explicitly install `python36-distro` instead of `python3-distro`. `yum` might not be smart enough to deterministically satisfy the dependency on its own.
If there's cache shenanigans at play here I'd be very surprised.

Regardless, I'll update the PR with the explicit `python36-distro`

**Comment by korydraughn** [comment]
Pulled your latest change and trying again.

**Review by alanking — APPROVED** [review]
Seems good to me

**Comment by SwooshyCueb** [comment]
If there are no objections, I will \#

**Review by korydraughn — APPROVED** [review]
Add the pounds.

**Pull request merged**
