### PR TITLE
[95] Add runner and debugger images for Ubuntu Jammy

### PR DESCRIPTION
**Pull request by SwooshyCueb**

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Looks good at a glance. Please ping when confirmed working/ready for review

**Comment by alanking** [comment]
Any progress here? Just making sure we don't lose this.

**Comment by SwooshyCueb** [comment]
Oh, I thought these were already merged. I'll test them on Monday

**Review by alanking — APPROVED** [review]
Looks good to me. Please # when ready

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
