### PR TITLE
Allow swapping out python versions and irods_python_ci_utilities for builders, and fix cen7 plugin builder

### PR DESCRIPTION
**Pull request by alanking**

### CODE REVIEW

**Comment by alanking** [comment]
We will probably need to merge this and/or #44 in the run up to the 4.3.0 release. We need to be able to build plugins for centos:7.

**Comment by korydraughn** [comment]
Are we happy with the changes? Does it all work?

**Comment by alanking** [comment]
Yeah, I think so. I'm able to build plugins on main and 4-2-stable for all the platforms that have plugin builders. I'm sure @SwooshyCueb has opinions about the formatting, but these changes will perhaps be overshadowed by the other PR :p

**Comment by alanking** [comment]
To avoid a hairy merge conflict, it may be better to merge #44 first if we are confident in it and then I can rebase this small change on top and deal with the fallout. Thoughts?

**Comment by korydraughn** [comment]
Sounds good. Will wait for #44.

**Pull request closed without merging**
